name: Deploy Snapshot
on:
  push:
    branches:
      - 'old-nbt'

jobs:
  deploy:
    uses: CloudburstMC/BlockStateUpdater/.github/workflows/deploy.yml@master
    with:
      deploy-url: "https://repo.mznt.eu/snapshots"
    secrets:
      DEPLOY_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      DEPLOY_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      PGP_SECRET: ${{ secrets.MAVEN_CENTRAL_SECRET }}
      PGP_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_PASSPHRASE }}
